### ISSUE TITLE
Question: docs for npm hooks?

### ISSUE THREAD

**Issue by rstacruz** [HashNuke/asdf-nodejs#12]
Hey, I'm trying to figure out how to implement #11 and I can't seem to find any docs on how the postinstall hook works. Can you point me to some documentation on them?

I tried adding an npm link hook and it didn't work.

**Comment by rstacruz** [comment]
nevermind, found it! https://docs.npmjs.com/misc/scripts

I guess npm link hooks aren't supported exactly.

**Comment by HashNuke** [comment]
@rstacruz Was looking into it yesterday. I didn't find any hooks (other than some discussion pages).
Any other course of action you have in mind? (like a note for those using npm-link as to how else to use it).

**Comment by rstacruz** [comment]
Maybe a manual "asdf reshim nodejs" that scans global node_modules for any
linkable packages? I know there's reshim but it doesn't work this way.

Or you can hook the npm shim to a custom shell script that intercepts "npm
link".

**Comment by HashNuke** [comment]
@rstacruz We could implement "asdf reshim nodejs" instead.

**Comment by HashNuke** [comment]
Closing this issue to continue conversation on #11
