### ISSUE TITLE
Binary name needs to be picked up from package.json's "bin" key

### ISSUE THREAD

**Issue by justin-calleja** [HashNuke/asdf-nodejs#4]
Hi again @HashNuke 

If you try installing live-server with `npm install -g live-server` you should get `live-server.js` in shims, passing "npm/bin/live-server.js" to nodejs plugin.

The actual binary's name is `live-server` in <node-version>.npm/bin

These names can be picked out from the package's package.json under the "bin" key. For live-server it's:

```json
"bin": {
	"live-server": "./live-server.js"
},
```

so the script's name will be "live-server". I'm not sure if you can add this reading of package.json as an additional test to determine $executable_name ?

I'm doing this: `$(basename ${bin_env_parts[1]} .js)` to truncate the .js extension when setting `executable_name` - generally, they're not installed with extension... but obviously this is not a proper solution. Just suggesting a "maybe good enough temporary fix" for the time being.

Cheers

**Comment by HashNuke** [comment]
@justin-calleja thank you for reporting this.
We don't read package.json because reading json in Bash... :)
So we parse the $bin_env. Please do send a PR with the fix you have. The temporary fix is actually our required fix.

**Comment by justin-calleja** [comment]
Done :smile:
