### ISSUE TITLE
json-server is installed as "index"

### ISSUE THREAD

**Issue by justin-calleja** [HashNuke/asdf-nodejs#6]
When installing [json-server](https://github.com/typicode/json-server), current version of this plugin installs the following file: 

    $ cat .asdf/shims/index
    #!/usr/bin/env bash
    exec /Users/justin/.asdf/bin/private/asdf-exec nodejs .npm/bin/index "$@"

The shim file should be named "json-server", and so should the path ".npm/bin/json-server".

It would then work as it is correctly installed in `.asdf/installs/nodejs/4.2.1/.npm/lib/node_modules/json-server`

I started trying to figure out a solution for this but haven't finished it. Opening issue so maybe someone can finish this.

In this plugin's `postinstall`, I was trying to set `executable_name` from `npm view`'s output instead of an env variable.

Something like: `npm view json-server bin --json | tr -d '{} \n' | cut -d\" -f2` which outputs `json-server`.

I'm not sure how to make the "json-server" arg to `npm view` generic (and it could include a version or whatever else npm supports when doing `npm install` - e.g. git commit hash?). I *think* `npm view` should still be able to give the same output when using things like git commit hashes (haven't tried it). I would assume it would pick the "bin" entry in package.json for that commit.

I *have* tried it with a module which uses "shorthand notation" to specify it's `bin` file e.g.

    $ cat package.json
    {
        "name": "renamer",
         "bin": "./index.js",
    ...
    $ npm view ./package.json bin --json | tr -d '{} \n' | cut -d\" -f2
    renamer

i.e. it works even though "bin" is not an object with key "renamer" and value "./index.js".

---

There is this env variable when the `postinstall` runs:

`npm_config_argv={"remain":["json-server"],"cooked":["install","--global","json-server"],"original":["install","-g","json-server"]}`

Not sure if one can count on always parsing the "remain" value to then pass it to `npm view`...

**Comment by HashNuke** [comment]
@justin-calleja just did some searching/comparing with previous issue

From what I understand now: If the `bin` property is specified as a hash in package.json like the following:
```
"bin": {
    "live-server": "./live-server.js"
}
```
then the binary name specified is used.

If it is specified as a key-value like the following
``
"bin": "./bin/index.js"
```
then it uses the package name.

I'm open to suggestions or fixes. You seem to have found a possible solution with the `npm view` trick anyway.

P.S: I haven't even read your issue completely just went on info-hiking on excitement.

**Comment by HashNuke** [comment]
@justin-calleja Ah. I'll wake up and fix this. There's definitely a solution.

**Comment by justin-calleja** [comment]
@HashNuke I'll have to look a bit into it myself. I *think*, when `npm` installs globally with `npm install -g <module-name>`, it does this:

When "bin" is an object:

```json
"bin": {
  "script-name": "./lib/someNodeFile.js"
}
```
`npm` will globally install (create) a link-file named "script-name".

When "bin" is a string:

```json
"bin": "./lib/someNodeFile.js"
```
 `npm` will install a link-file with the name of the module (e.g. say "name" is "script-name" in package.json).

*Where* this file is installed by `npm`, I'm not sure - I mean I know I can look it up for my setup with `which live-server` - but it would give me: "/Users/justin/.asdf/shims/live-server" - i.e. not sure what someone not using `asdf` would get (probably somewhere which needs `sudo` access...).

In any case, wherever they're installed, they're on the PATH, and they link to the module's actual script file wherever the module itself gets globally installed on the system: /usr/... /script-name/lib/someNodeFile.js which probably has a "run with node shebang".

Thanks for always quickly replying and helping out!! But no rush really, take your time. I know how to manually fix things and get my global modules installed (the shim changes).

Cheers!

**Comment by HashNuke** [comment]
The executable file name was earlier sourced from the node_bin_env (if
that's what it's called. I would suggest tinkering the postinstall hook and
echo-ing that var. It'll dump a lot of info when npm install happens.
Easier to look at env vars and debug.

P.S: Warning: when I said lot of info. I mean LOTS of info :)

**Comment by justin-calleja** [comment]
Well, there is an `npm_package_name=json-server` in that output which is
exactly what we need in this case... but will the package name always be
the name of the link file? Since it's "package_name" I'm thinking that the
module writer could name the module x and have "bin": { "y":
"./bin/index.js" }. In this case, we need "y" not "x", because in
<node-install>/.npm/bin there will be "y" not "x".

$bin_env in `postinstall` is:

npm_package_bin_json_server=./bin/index.js

which is the module's "bin" file (but not the link file's name) i.e. that
would be what "y" links to.

I will have to try it out with some dummy modules I create or happen to
find (to see what happens in the x / y scenario above). If in the x / y
scenario, `npm_package_name` happens to be "y" not "x", we're good to use
that I think.


On 13 December 2015 at 19:07, Akash Manohar <notifications@github.com>
wrote:

> The executable file name was earlier sourced from the node_bin_env (if
> that's what it's called. I would suggest tinkering the postinstall hook and
> echo-ing that var. It'll dump a lot of info when npm install happens.
> Easier to look at env vars and debug.
>
> P.S: Warning: when I said lot of info. I mean LOTS of info :)
>
> On Sun, Dec 13, 2015 at 11:32 PM, Justin Calleja <notifications@github.com
> >
> wrote:
>
> > @HashNuke <https://github.com/HashNuke> I'll have to look a bit into it
> > myself. I *think*, when npm installs globally with npm install -g
> > <module-name>, it does this:
> >
> > When "bin" is an object:
> >
> > "bin": {
> > "script-name": "./lib/someNodeFile.js"
> > }
> >
> > npm will globally install (create) a link-file named "script-name".
> >
> > When "bin" is a string:
> >
> > "bin": "./lib/someNodeFile.js"
> >
> > npm will install a link-file with the name of the module (e.g. say "name"
> > is "script-name" in package.json).
> >
> > *Where* this file is installed by npm, I'm not sure - I mean I know I can
> > look it up for my setup with which live-server - but it would give me:
> > "/Users/justin/.asdf/shims/live-server" - i.e. not sure what someone not
> > using asdf would get (probably somewhere which needs sudo access...).
> >
> > In any case, wherever they're installed, they're on the PATH, and they
> > link to the module's actual script file wherever the module itself gets
> > globally installed on the system: /usr/...
> /script-name/lib/someNodeFile.js
> > which probably has a "run with node shebang".
> >
> > Thanks for always quickly replying and helping out!! But no rush really,
> > take your time. I know how to manually fix things and get my global
> modules
> > installed (the shim changes).
> >
> > Cheers!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/HashNuke/asdf-nodejs/issues/6#issuecomment-164284142
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HashNuke/asdf-nodejs/issues/6#issuecomment-164284350>.
>



-- 

Regards,
Justin

**Comment by justin-calleja** [comment]
Ok... unfortunately `npm_package_name` won't do.

Here's a quick module to test this out:

In a clean directory (name doesn't matter):

    $ find .
    .
    ./bin
    ./bin/index.js
    ./package.json
    ./src
    ./src/cli
    ./src/cli/index.js

It's a bit over-complicated but it mirrors "json-server"'s set up (which isn't what this is about anymore - but what the heck).

package.json:

```json
{
  "name": "abc",
  "bin": {
    "woo-tmp": "./bin/index.js"
  }
}
```

```
cat bin/index.js
#!/usr/bin/env node
require('../src/cli')()
````
```
cat src/cli/index.js
module.exports = function() {
  console.log('this is the abc module');
}
```

If you run `npm install -g` at the project home, you'll end up installing "index" in shims, just like json-server.

`npm_package_name` will be `abc` (unfortunately) in env in postinstall. This means we cannot use it because we want "woo-tmp" to go in "shims" and for the shim to have this content:

```
#!/usr/bin/env bash
exec /Users/justin/.asdf/bin/private/asdf-exec nodejs .npm/bin/woo-tmp "$@"
```

because that will use <node-install>/.npm/woo-tmp which links to `../lib/node_modules/abc/bin/index.js`

**Comment by justin-calleja** [comment]
First of all, correction: This will *not* work: `npm view ./package.json`

It just so happened that there was a module named "renamer" in the npm registry and it was pulling that one in... i.e. `npm view` only seems to work against modules which have been published to the npm registry.

(also note re my example above, that a module named "abc" actually exists in the npm registry...)

Here is my attempt at fixing this:

https://github.com/justin-calleja/asdf-nodejs/commit/f9253122299febacc7b38d913745f77cef3d67eb

it is **not** guaranteed to work if the module being installed is not in the public npm registry. If it is not in the public npm registry, it will use the package's name as the executable's name, essentially defaulting to the shortcut value of "bin" in package.json.

i.e. if bin were:

```json
"bin": {
  "abcde":  "./bin/index.js"
}
```

then the package's name had better be "abcde", otherwise it won't work. Currently, though, asdf-nodejs is using "index" in this case which has less chance of being right. i.e. I haven't checked but I would imagine that it is usually the case that package name ends up being used for the executable name in most packages which install a script globally.

**Comment by HashNuke** [comment]
Fixed.
@justin-calleja check out the latest update and let me know if you have problems.
Uninstall and install your node.js version (the plugin now installs a central postinstall hook).

**Comment by justin-calleja** [comment]
Hi HashNuke,

After re-installing Node, I deleted some shims and ran: `npm install -g bower`

Although it installs successfully, this file is not created in shims/bower (so the command ends up being "not found"):

```bash
#!/usr/bin/env bash
exec /Users/justin/.asdf/bin/private/asdf-exec nodejs .npm/bin/bower "$@"
```

If I add it manually, it works.

**Comment by HashNuke** [comment]
@justin-calleja Fixed it. I used the wrong condition. Do `asdf plugin-update nodejs`

**Comment by justin-calleja** [comment]
@HashNuke awesome stuff! It's working and same for the package I originally opened this issue for (json-server).

Cheers!
